import './styles/globals.scss';

export const metadata = {
  title: 'Line-Store.vercel',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
